import {
  LucideAlertTriangle as AlertTriangle,
  LucideArrowLeft as ArrowLeft,
  LucideArrowRight as ArrowRight,
  LucideCheck as Check,
  LucideChevronDown as ChevronDown,
  LucideChevronLeft as ChevronLeft,
  LucideChevronRight as ChevronRight,
  LucideChevronUp as ChevronUp,
  LucideCircleCheck as CircleCheck,
  LucideCircleX as CircleX,
  LucideClock as Clock,
  LucideCopy as Copy,
  LucideExternalLink as ExternalLink,
  LucideEye as Eye,
  LucideEyeOff as EyeOff,
  LucideFilter as Filter,
  LucideGrid2x2 as Grid2x2,
  LucideHeart as Heart,
  LucideInfo as Info,
  LucideList as List,
  LucideLoader as Loader,
  LucideMapPin as MapPin,
  LucideMenu as Menu,
  LucideMinus as Minus,
  LucidePackage as Package,
  LucidePhone as Phone,
  LucidePlus as Plus,
  LucideScale as Scale,
  LucideSearch as Search,
  LucideSend as Send,
  LucideShare2 as Share2,
  LucideShoppingCart as ShoppingCart,
  LucideSlidersHorizontal as SlidersHorizontal,
  LucideSmartphone as Smartphone,
  LucideStar as Star,
  LucideTrash2 as Trash2,
  LucideTruck as Truck,
  LucideUser as User,
  LucideX as X,
} from '@lucide/angular';

// Brand/social icons removed from lucide — preserved as custom icon data.
import { Facebook, Instagram, Youtube } from './custom-icons';

export const APP_ICONS = {
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Eye,
  Instagram,
  Youtube,
  EyeOff,
  Heart,
  Phone,
  Scale,
  Search,
  Facebook,
  ShoppingCart,
  Smartphone,
  Star,
  Trash2,
  X,
  Plus,
  Minus,
  ArrowLeft,
  ArrowRight,
  Filter,
  SlidersHorizontal,
  Grid2x2,
  List,
  MapPin,
  Clock,
  Package,
  Send,
  Truck,
  CircleCheck,
  CircleX,
  Info,
  AlertTriangle,
  User,
  Menu,
  Share2,
  Copy,
  ExternalLink,
  Loader,
};
